function language_setup()
{
    try
    {
        const english =
        {
            tools_text: "TOOLS",
            tools_text_short: "TOOLS",
            translate_button_text: "TRANSLATE TO GREEK",
            back_button_text: "Back",
            search_the_bible_title: "Search the Bible",
            QuickNav: "QuickNav",
            Help: "Help",
            old_testament_title: "Old Testament",
            new_testament_title: "New Testament",
            genesis_short: "Gen",
            exodus_short: "Exo",
            leviticus_short: "Lev",
            numbers_short: "Num",
            deuteronomy_short: "Deu",
            joshua_short: "Jos",
            judges_short: "Jdg",
            ruth_short: "Rth",
            one_samuel_short: "1Sa",
            two_samuel_short: "2Sa",
            one_kings_short: "1Ki",
            two_kings_short: "2Ki",
            one_chronicles_short: "1Ch",
            two_chronicles_short: "2Ch",
            ezra_short: "Ezr",
            nehemiah_short: "Neh",
            esther_short: "Est",
            job_short: "Job",
            psalms_short: "Psa",
            proverbs_short: "Pro",
            ecclesiastes_short: "Ecc",
            song_of_songs_short: "Sng",
            isaiah_short: "Isa",
            jeremiah_short: "Jer",
            lamentations_short: "Lam",
            ezekiel_short: "Eze",
            daniel_short: "Dan",
            hosea_short: "Hos",
            joel_short: "Joe",
            amos_short: "Amo",
            obadiah_short: "Oba",
            jonah_short: "Jon",
            micah_short: "Mic",
            nahum_short: "Nah",
            habakkuk_short: "Hab",
            zephaniah_short: "Zep",
            haggai_short: "Hag",
            zechariah_short: "Zec",
            malachi_short: "Mal",
            matthew_short: "Mat",
            mark_short: "Mar",
            luke_short: "Luk",
            john_short: "Jhn",
            acts_short: "Act",
            romans_short: "Rom",
            one_corinthians_short: "1Co",
            two_corinthians_short: "2Co",
            galatians_short: "Gal",
            ephesians_short: "Eph",
            philippians_short: "Phl",
            colossians_short: "Col",
            one_thessalonians_short: "1Th",
            two_thessalonians_short: "2Th",
            one_timothy_short: "1Ti",
            two_timothy_short: "2Ti",
            titus_short: "Tit",
            philemon_short: "Phm",
            hebrews_short: "Heb",
            james_short: "Jas",
            one_peter_short: "1Pe",
            two_peter_short: "2Pe",
            one_john_short: "1Jo",
            two_john_short: "2Jo",
            three_john_short: "3Jo",
            jude_short: "Jde",
            revelation_short: "Rev",
            genesis_full: "Genesis",
            exodus_full: "Exodus",
            leviticus_full: "Leviticus",
            numbers_full: "Numbers",
            deuteronomy_full: "Deuteronomy",
            joshua_full: "Joshua",
            judges_full: "Judges",
            ruth_full: "Ruth",
            one_samuel_full: "1 Samuel",
            two_samuel_full: "2 Samuel",
            one_kings_full: "1 Kings",
            two_kings_full: "2 Kings",
            one_chronicles_full: "1 Chronicles",
            two_chronicles_full: "2 Chronicles",
            ezra_full: "Ezra",
            nehemiah_full: "Nehemiah",
            esther_full: "Esther",
            job_full: "Job",
            psalms_full: "Psalms",
            proverbs_full: "Proverbs",
            ecclesiastes_full: "Ecclesiastes",
            song_of_songs_full: "Song of Songs",
            isaiah_full: "Isaiah",
            jeremiah_full: "Jeremiah",
            lamentations_full: "Lamentations",
            ezekiel_full: "Ezekiel",
            daniel_full: "Daniel",
            hosea_full: "Hosea",
            joel_full: "Joel",
            amos_full: "Amos",
            obadiah_full: "Obadiah",
            jonah_full: "Jonah",
            micah_full: "Micah",
            nahum_full: "Nahum",
            habakkuk_full: "Habakkuk",
            zephaniah_full: "Zephaniah",
            haggai_full: "Haggai",
            zechariah_full: "Zechariah",
            malachi_full: "Malachi",
            matthew_full: "Matthew",
            mark_full: "Mark",
            luke_full: "Luke",
            john_full: "John",
            acts_full: "Acts",
            romans_full: "Romans",
            one_corinthians_full: "1 Corinthians",
            two_corinthians_full: "2 Corinthians",
            galatians_full: "Galatians",
            ephesians_full: "Ephesians",
            philippians_full: "Philippians",
            colossians_full: "Colossians",
            one_thessalonians_full: "1 Thessalonians",
            two_thessalonians_full: "2 Thessalonians",
            one_timothy_full: "1 Timothy",
            two_timothy_full: "2 Timothy",
            titus_full: "Titus",
            philemon_full: "Philemon",
            hebrews_full: "Hebrews",
            james_full: "James",
            one_peter_full: "1 Peter",
            two_peter_full: "2 Peter",
            one_john_full: "1 John",
            two_john_full: "2 John",
            three_john_full: "3 John",
            jude_full: "Jude",
            revelation_full: "Revelation",
        }
        const greek =
        {
            tools_text: "ΕΡΓΑΛΕΙΑ",
            tools_text_short: "ΕΡΓ...",
            translate_button_text: "ΜΕΤΑΦΡΑΣΤΕ ΤΟ ΣΤΑ ΕΛΛΗΝΙΚΑ",
            back_button_text: "Πίσω",
            search_the_bible_title: "Αναζήτησε την Αγία Γραφή",
            QuickNav: "Πλοήγηση",
            Help: "Βοήθεια",
            old_testament_title: "Παλαιά Διαθήκη",
            new_testament_title: "Καινή Διαθήκη",
            genesis_short: "ΓΕΝ",
            exodus_short: "ΕΞΟ",
            leviticus_short: "ΛΕΥ",
            numbers_short: "ΑΡΙ",
            deuteronomy_short: "ΔΕΥ",
            joshua_short: "ΙΗΣ",
            judges_short: "ΚΡΙ",
            ruth_short: "ΡΟΥ",
            one_samuel_short: "Α΄ΣΑ",
            two_samuel_short: "Β΄ΣΑ",
            one_kings_short: "Α΄ΒΑ",
            two_kings_short: "Β΄ΒΑ",
            one_chronicles_short: "Α΄ΧΡ",
            two_chronicles_short: "Β΄ΧΡ",
            ezra_short: "ΕΣΔ",
            nehemiah_short: "ΝΕΕ",
            esther_short: "ΕΣΘ",
            job_short: "ΙΩΒ",
            psalms_short: "ΨΑΛ",
            proverbs_short: "ΠΑΡ",
            ecclesiastes_short: "ΕΚΚ",
            song_of_songs_short: "ΑΣΜ",
            isaiah_short: "ΗΣΑ",
            jeremiah_short: "ΙΕΡ",
            lamentations_short: "ΘΡΗ",
            ezekiel_short: "ΙΕΖ",
            daniel_short: "ΔΑΝ",
            hosea_short: "ΟΣΗ",
            joel_short: "ΙΩΗ",
            amos_short: "ΑΜΩ",
            obadiah_short: "ΟΒΔ",
            jonah_short: "ΙΩΝ",
            micah_short: "ΜΙΧ",
            nahum_short: "ΝΑΟ",
            habakkuk_short: "ΑΒΒ",
            zephaniah_short: "ΣΟΦ",
            haggai_short: "ΑΓΓ",
            zechariah_short: "ΖΑΧ",
            malachi_short: "ΜΑΛ",
            matthew_short: "ΜΑΤ",
            mark_short: "ΜΑΡ",
            luke_short: "ΛΟΥ",
            john_short: "ΙΩΑ",
            acts_short: "ΠΡΑ",
            romans_short: "ΡΩΜ",
            one_corinthians_short: "Α΄ΚΟ",
            two_corinthians_short: "Β΄ΚΟ",
            galatians_short: "ΓΑΛ",
            ephesians_short: "ΕΦΕ",
            philippians_short: "ΦΙΛ",
            colossians_short: "ΚΟΛ",
            one_thessalonians_short: "Α΄ΘΕ",
            two_thessalonians_short: "Β΄ΘΕ",
            one_timothy_short: "Α΄ΤΙ",
            two_timothy_short: "Β΄ΤΙ",
            titus_short: "ΤΙΤ",
            philemon_short: "ΦΙΛ",
            hebrews_short: "ΕΒΡ",
            james_short: "ΙΑΚ",
            one_peter_short: "Α΄ΠΕ",
            two_peter_short: "Β΄ΠΕ",
            one_john_short: "Α΄ΙΩ",
            two_john_short: "Β΄ΙΩ",
            three_john_short: "Γ΄ΙΩ",
            jude_short: "ΙΟΥ",
            revelation_short: "ΑΠΟ",
            genesis_full: "ΓΕΝΕΣΙΣ",
            exodus_full: "ΕΞΟΔΟΣ",
            leviticus_full: "ΛΕΥΙΤΙΚΟΝ",
            numbers_full: "ΑΡΙΘΜΟΙ",
            deuteronomy_full: "ΔΕΥΤΕΡΟΝΟΜΙΟΝ",
            joshua_full: "ΙΗΣΟΥΣ ΤΟΥ ΝΑΥΗ",
            judges_full: "ΚΡΙΤΑΙ",
            ruth_full: "ΡΟΥΘ",
            one_samuel_full: "Α΄ ΣΑΜΟΥΗΛ",
            two_samuel_full: "Β΄ ΣΑΜΟΥΗΛ",
            one_kings_full: "Α΄ ΒΑΣΙΛΕΩΝ",
            two_kings_full: "Β΄ ΒΑΣΙΛΕΩΝ",
            one_chronicles_full: "Α΄ ΧΡΟΝΙΚΩΝ",
            two_chronicles_full: "Β΄ ΧΡΟΝΙΚΩΝ",
            ezra_full: "ΕΣΔΡΑΣ",
            nehemiah_full: "ΝΕΕΜΙΑΣ",
            esther_full: "ΕΣΘΗΡ",
            job_full: "ΙΩΒ",
            psalms_full: "ΨΑΛΜΟΙ",
            proverbs_full: "ΠΑΡΟΙΜΙΑΙ",
            ecclesiastes_full: "ΕΚΚΛΗΣΙΑΣΤΗΣ",
            song_of_songs_full: "ΑΣΜΑ ΑΣΜΑΤΩΝ",
            isaiah_full: "ΗΣΑΪΑΣ",
            jeremiah_full: "ΙΕΡΕΜΙΑΣ",
            lamentations_full: "ΘΡΗΝΟΙ",
            ezekiel_full: "ΙΕΖΕΚΙΗΛ",
            daniel_full: "ΔΑΝΙΗΛ",
            hosea_full: "ΩΣΗΕ",
            joel_full: "ΙΩΗΛ",
            amos_full: "ΑΜΩΣ",
            obadiah_full: "ΟΒΔΙΟΥ",
            jonah_full: "ΙΩΝΑΣ",
            micah_full: "ΜΙΧΑΙΑΣ",
            nahum_full: "ΝΑΟΥΜ",
            habakkuk_full: "ΑΒΒΑΚΟΥΜ",
            zephaniah_full: "ΣΟΦΟΝΙΑΣ",
            haggai_full: "ΑΓΓΑΙΟΣ",
            zechariah_full: "ΖΑΧΑΡΙΑΣ",
            malachi_full: "ΜΑΛΑΧΙΑΣ",
            matthew_full: "ΚΑΤΑ ΜΑΤΘΑΙΟΝ",
            mark_full: "ΚΑΤΑ ΜΑΡΚΟΝ",
            luke_full: "ΚΑΤΑ ΛΟΥΚΑΝ",
            john_full: "ΚΑΤΑ ΙΩΑΝΝΗΝ",
            acts_full: "ΠΡΑΞΕΙΣ ΑΠΟΣΤΟΛΩΝ",
            romans_full: "ΠΡΟΣ ΡΩΜΑΙΟΥΣ",
            one_corinthians_full: "ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Α΄",
            two_corinthians_full: "ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Β΄",
            galatians_full: "ΠΡΟΣ ΓΑΛΑΤΑΣ",
            ephesians_full: "ΠΡΟΣ ΕΦΕΣΙΟΥΣ",
            philippians_full: "ΠΡΟΣ ΦΙΛΙΠΠΗΣΙΟΥΣ",
            colossians_full: "ΠΡΟΣ ΚΟΛΟΣΣΑΕΙΣ",
            one_thessalonians_full: "ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Α΄",
            two_thessalonians_full: "ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Β΄",
            one_timothy_full: "Α΄ ΠΡΟΣ ΤΙΜΟΘΕΟΝ",
            two_timothy_full: "Β΄ ΠΡΟΣ ΤΙΜΟΘΕΟΝ",
            titus_full: "ΠΡΟΣ ΤΙΤΟΝ",
            philemon_full: "ΠΡΟΣ ΦΙΛΗΜΟΝΑ",
            hebrews_full: "ΠΡΟΣ ΕΒΡΑΙΟΥΣ",
            james_full: "ΙΑΚΩΒΟΥ",
            one_peter_full: "Α΄ ΠΕΤΡΟΥ",
            two_peter_full: "Β΄ ΠΕΤΡΟΥ",
            one_john_full: "Α΄ ΙΩΑΝΝΟΥ",
            two_john_full: "Β΄ ΙΩΑΝΝΟΥ",
            three_john_full: "Γ΄ ΙΩΑΝΝΟΥ",
            jude_full: "ΙΟΥΔΑ",
            revelation_full: "ΑΠΟΚΑΛΥΨΗ ΙΩΑΝΝΟΥ"
        };
        let language = "greek";
        if(language == "greek")
        {
            return greek;
        }
        elif(language == "english")
        {
            return english;
        }
    }
    catch(err){}
}
